services:
  user-service:
    restart: always
    image: eyidana/user-service-java:0.01
    container_name: user-service
    build:
      context: ./user-service
      dockerfile: ./Dockerfile
    depends_on:
      - config-server
    ports:
      - "9090:9090"
    networks:
      - travel-net

  booking-service:
    restart: always
    image: eyidana/booking-service-java:0.01
    container_name: booking-service
    build:
      context: ./booking-service
      dockerfile: ./Dockerfile
    depends_on:
      - config-server
    ports:
      - "9095:9095"
    networks:
      - travel-net

  # flight-service:
  #   restart: always
  #   image: eyidana/flight-service-java:0.01
  #   container_name: flight-service
  #   build:
  #     context: ./flight-service
  #     dockerfile: ./Dockerfile
  #   depends_on:
  #     - config-server
  #   ports:
  #     - "9091:9091"
  #   networks:
  #     - travel-net

  payment-service:
    restart: always
    image: eyidana/payment-service-java:0.01
    container_name: payment-service
    build:
      context: ./payment-service
      dockerfile: ./Dockerfile
    depends_on:
      - config-server
    ports:
      - "9093:9093"
    networks:
      - travel-net

  api-gateway:
    restart: always
    image: eyidana/api-gateway-java:0.01
    container_name: api-gateway
    build:
      context: ./api-gateway
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    networks:
      - travel-net

  service-registry:
    restart: always
    image: eyidana/service-registry-java:0.01
    container_name: service-registry
    build:
      context: ./service-registry
      dockerfile: ./Dockerfile
    ports:
      - "8761:8761"
    networks:
      - travel-net

  config-server:
    restart: always
    image: eyidana/config-server-java:0.01
    container_name: config-server
    build:
      context: ./config-server
      dockerfile: ./Dockerfile
    ports:
      - "8888:8888"
    networks:
      - travel-net

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      - travel-net

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: keycloak
    command: start-dev
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - travel-net

networks:
  travel-net:
    driver: bridge